### ISSUE TITLE
Adding a question: "abschicken" and "abbrechen" button overlap

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#130]
On a smaller screen, the button "abschicken" and "abbrechen" overlap (Firefox)

<img width="419" alt="Bildschirmfoto 2019-05-02 um 14 21 56" src="https://user-images.githubusercontent.com/30862422/57076210-5faf1400-6ce9-11e9-8ad4-89f0d351d36a.png">

**Comment by fuzzylogic2000** [comment]
@phillimorland It's a German thing again....
