### ISSUE TITLE
Login displays weirdly

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#131]
The login gets weird when clicking on it in order to log in. 

<img width="419" alt="Bildschirmfoto 2019-05-02 um 14 22 58" src="https://user-images.githubusercontent.com/30862422/57076503-1f9c6100-6cea-11e9-897d-2df9e20ce56a.png">

**Comment by hmkay** [comment]
And I even have to click twice...?

<img width="498" alt="Bildschirmfoto 2019-05-02 um 14 57 24" src="https://user-images.githubusercontent.com/30862422/57076788-bb2dd180-6cea-11e9-934b-888a57633245.png">

**Comment by phillimorland** [comment]
@hmkay can you add screen size/s and browser for issues like this? it just speeds up fix when we know where to look :)

**Comment by hmkay** [comment]
@phillimorland sorry!! Of course. I will do it next itme! Or do you need it still now? Then I´ll try to find it...

**Comment by phillimorland** [comment]
nah found it, cheers!
