### ISSUE TITLE
Info-Tab: no text editable

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#132]
As an admin, I cannot add the text for the info tab

<img width="1068" alt="Bildschirmfoto 2019-05-02 um 15 02 02" src="https://user-images.githubusercontent.com/30862422/57077073-63439a80-6ceb-11e9-9fd3-72c1f3633be3.png">

**Comment by hmkay** [comment]
haha, I cant even make a new project because the info-tab is compulsory xD

**Comment by fuzzylogic2000** [comment]
fixed by downdating ckeditor again
