### ISSUE TITLE
update ckeditor

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#134]
When updating the ckeditor from 5.6.1. to 5.7.0, and once deployed it breaks with

`Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
The resource from “https://meinberlin-dev.liqd.net/dashboard/projects/blalal/information/config.js?t=I3I8” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).[Learn More] information
Loading failed for the <script> with source “https://meinberlin-dev.liqd.net/dashboard/projects/blalal/information/config.js?t=I3I8”. information:1:1
The resource from “https://meinberlin-dev.liqd.net/dashboard/projects/blalal/information/skins/moono-lisa/editor_gecko.css?t=I3I8” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).[Learn More] information
The resource from “https://meinberlin-dev.liqd.net/dashboard/projects/blalal/information/lang/de.js?t=I3I8” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).[Learn More] information
Loading failed for the <script> with source “https://meinberlin-dev.liqd.net/dashboard/projects/blalal/information/lang/de.js?t=I3I8”. information:1:1
TypeError: c[a] is undefined[Learn More] ckeditor.7e12b0b75d20.js:249:46
    d https://meinberlin-dev.liqd.net/static/ckeditor/ckeditor/ckeditor.7e12b0b75d20.js:249
    e https://meinberlin-dev.liqd.net/static/ckeditor/ckeditor/ckeditor.7e12b0b75d20.js:250
    z https://meinberlin-dev.liqd.net/static/ckeditor/ckeditor/ckeditor.7e12b0b75d20.js:250
    y https://meinberlin-dev.liqd.net/static/ckeditor/ckeditor/ckeditor.7e12b0b75d20.js:250
    onerror https://meinberlin-dev.liqd.net/static/ckeditor/ckeditor/ckeditor.7e12b0b75d20.js:251`

@treba123 Any ideas?

**Comment by treba123** [comment]
I guess `(X-Content-Type-Options: nosniff)` is the important part. Will look into it.

**Comment by treba123** [comment]
Actually this looks like an old friend: ckeditor not using the static folder but just searching for config.js at the end of the path....
