### ISSUE TITLE
presentation screen: Info about Event

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#253]
In the design, there was information about the event (date, place). Do we include that? Is that possible?

**Comment by hmkay** [comment]
@MagdaN @phillimorland : What are we doing with this? Or shall we leave it so far and I talk about it tomorrow with @fuzzylogic2000 ?

**Comment by MagdaN** [comment]
there is no possibility to add a place (but if you see the screen, I guess you found it?) at the moment, we could add the date

**Comment by hmkay** [comment]
Ok, to be honest: it wasn´t mentioned in the acceptance criteria. So maybe leave it for now. If it is easy to do and you think it is worth it, then feel free ;)

**Comment by MagdaN** [comment]
@phillimorland is there an easy way to change this?

**Comment by hmkay** [comment]
i wrote a story about it, done.
