### ISSUE TITLE
Moderators view: wording info abt icons

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#257]
Suggestions for the new wording and German wording for the explanaition of the icons:

Shortlist: add question to shortlist // Frage zur Redeliste hinzufügen
presentation screen: display question on screen // Frage auf dem Bildschim anzeigen
answered: mark question as answered // Frage als beantwortet makieren
hide: hide question from audience // Frage vor dem Publikum verbergen

**Comment by hmkay** [comment]
@MagdaN : As an info for you regarding the wording :)

**Comment by MagdaN** [comment]
@hmkay we are on it!

**Comment by hmkay** [comment]
@MagdaN : this might be just a little "kleinkariert", but could you also check that within the info box the icons and wording are aligned?

**Comment by hmkay** [comment]
![Bildschirmfoto 2019-08-28 um 14 03 11](https://user-images.githubusercontent.com/30862422/63854086-95fd5700-c99c-11e9-8d81-29f23501454e.png)

**Comment by hmkay** [comment]
the icons appear to be different sizes...you knw what I mean?

**Comment by phillimorland** [comment]
note: icons are now same size
