### ISSUE TITLE
show hidden questions after answered questions in statistics view

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#259]
When the questions are mixed, the title does not fit anymore and I find it confusing.

**Comment by fuzzylogic2000** [comment]
Also, it might be confusing that the hidden questions are there anyway. Could we keep them in the normal list, but only show to moerators? And maybe put in a filter for the moderators? Or move them to the end? @hmkay @MagdaN Let's talk about it (again) before we implement more!

**Comment by hmkay** [comment]
@fuzzylogic2000 @MagdaN : it was for moderators view only. But I do get that it is confusing either way. What do we need to close the story? Can we do something easy that we could have for now and adapt later?

**Comment by fuzzylogic2000** [comment]
@hmkay Well, I would say it is currently like we said it would be, so we can close the story. But I still think, we should make it better in the next Speakup-sprint because it doesn't make us happy like that. We have to refactor anyway and instead of doing that and then doing it again, I#d say we come up with a solution we are happy with and then do it?!

**Comment by fuzzylogic2000** [comment]
@hmkay @MagdaN @phillimorland I think you already fixed it? Can we close this issue?

**Comment by hmkay** [comment]
Yes! Closed with a new filter system!
