### ISSUE TITLE
change marked-choice thing to round button with a fa-bookmark

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#28]
active: orange
inactive: blue

**Comment by MagdaN** [comment]
we should in general come up with a solution for how to display the sorting button and the bookmark button

**Comment by MagdaN** [comment]
@fuzzylogic2000 I added this to the release and I think it would be really nice to have it but if it is to complicated just remove the milestone from this issue

**Comment by fuzzylogic2000** [comment]
@szukowski So, this was about the first checkbox "only display marked questions". You had the idea to just have a button that's either active or inactive with the marked-icon on it. Nice solution!
But now we have a second checkbox (images) to sort by most likes. This can't become another active/inactive button as that would be hard to understand. What do we do? 
Add another dropdown for the sorting maybe?

![Screenshot from 2019-04-24 10-34-13](https://user-images.githubusercontent.com/8178179/56664439-5ea63300-66a8-11e9-8b5f-4a700166d54a.png)
![Screenshot from 2019-04-24 10-33-40](https://user-images.githubusercontent.com/8178179/56664440-5ea63300-66a8-11e9-8a70-762e77bc0a41.png)

**Comment by szukowski** [comment]
![grafik](https://user-images.githubusercontent.com/36926290/56739507-19990400-676f-11e9-9c95-985100b71998.png)
@fuzzylogic2000

**Comment by fuzzylogic2000** [comment]
@szukowski Nice! Thanks! So these also get to be orange when they are activated?

**Comment by szukowski** [comment]
@fuzzylogic2000 Yes
