### ISSUE TITLE
Helptext to explain user List-Icon

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#287]
Users apparently do not understand if a list-icon is in front of their question. Could we make another infobox to that? Or a short infotext? Is this a Story?

**Comment by hmkay** [comment]
@MagdaN @phillimorland @fuzzylogic2000 : Still not sure if this is a story?

**Comment by phillimorland** [comment]
@hmkay what should the info text say?

**Comment by hmkay** [comment]
https://giphy.com/gifs/p77ClDx5Qufm0/html5

**Comment by hmkay** [comment]
http://giphygifs.s3.amazonaws.com/media/p77ClDx5Qufm0/giphy.gif

**Comment by hmkay** [comment]
<iframe src="https://giphy.com/embed/p77ClDx5Qufm0" width="480" height="253" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/fox-p77ClDx5Qufm0">via GIPHY</a></p>

**Comment by hmkay** [comment]
https://media.giphy.com/media/p77ClDx5Qufm0/source.gif

**Comment by hmkay** [comment]
Does it include the Icon? Then:
"[Icon] Diese Frage ist auf der Redeliste der Moderation."
