### ISSUE TITLE
statistics: display some kind of explanation/info-text 

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#30]
There could be some text below statistics, but we might need more text or a headline to say that the questions are the answered ones

**Comment by fuzzylogic2000** [comment]
@hmkay Could you provide a text?

**Comment by hmkay** [comment]
@fuzzylogic2000 YES! It is:
"Einbezogene Beiträge"

**Comment by fuzzylogic2000** [comment]
@hmkay Weeeell, we don't have translations yet... What would that be in English?
