### ISSUE TITLE
time setting of moderation invite is not UTC+1

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#305]
URL: hhttps://speakup.digital/dashboard/projects/eure-fragen-zu-speakup/moderators/
user: initiator
expected behaviour: next to the "ausstehende Einladung" the correct UTC+1 time is given.
behaviour: It is two hours late
device & browser: Desktop, firefox 68.0.2 (64-Bit)
Importance: enhancement
![Bildschirmfoto 2019-09-09 um 14 14 39](https://user-images.githubusercontent.com/30862422/64529878-32641980-d30c-11e9-8297-5176eff90fd4.png)

**Comment by fuzzylogic2000** [comment]
I think this should also have been fixed by #336 - will quickly test that!

**Comment by fuzzylogic2000** [comment]
Yep! Fixed!
