### ISSUE TITLE
info box for user: wording and behaviour should change

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#307]
**URL:** https://speakup.digital/projects/eure-fragen-zu-speakup/
**user:** user, not logged in
**expected behaviour:** German description: "question has been added to shortlist" = "Frage ist von der Moderation vorgemerkt"
**behaviour:** missing translation
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)
**Importance:** relevant for Sprint

**Comment by hmkay** [comment]
I guess the whole description has to change, as the symbol isn´t clear when it doesn´t appear nowhere. Suggestion:
- The infobox is always closed
- If user opens it, infobox says:
"Du siehst dieses ** Symbol vor einer Frage? Dann wurde sie von der Moderation vorgemerkt."

**Comment by hmkay** [comment]
What do you think, @fuzzylogic2000 ?

**Comment by fuzzylogic2000** [comment]
Ehm, this is two issues, isn't it? 
But I think you're right. It's better to behave like you suggest. Will change that!

**Comment by fuzzylogic2000** [comment]
Oh, putting the icon in the text might change the styling.
So, what about: 
"** wird vor einer Frage angezeigt? Dann wurde sie von der Moderation vorgemerkt."
I can try the other one first, though.
