### ISSUE TITLE
user view: reloading question pages makes info box reappear

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#309]
**URL:** https://speakup.digital/projects/eure-fragen-zu-speakup/
**user:** moderation
**expected behaviour:** The info box "questions has been added to shortlist" is usually closed. After I closed it the first time, I expect it to stay close also after I added a question and got back on the question side.
**behaviour:** The info box re-opens if the user added a question.
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)
**Importance:** Would improve usability, would be nice to have it fixed before the first use next week....if possible =)

**Comment by fuzzylogic2000** [comment]
Adding a question reloads the side, so this makes sense. But will be changed with the other issue with the same topic
