### ISSUE TITLE
statistics: display orange (active) checkmark on answered questions

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#31]

**Comment by phillimorland** [comment]
@fuzzylogic2000 haven't all questions in the statistics tab been answered? or have i missed something?

**Comment by fuzzylogic2000** [comment]
@phillimorland No, that is right! It was meant to make clear why the questions were in this tab. But with #30 solved, this issue might not be important anymore (for now)!

**Comment by fuzzylogic2000** [comment]
Fine now!
