### ISSUE TITLE
moderation function

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#310]
**URL:** https://speakup.digital/projects/eure-fragen-zu-speakup/
**user:** moderation
**expected behaviour:** I can moderate the incoming questions
**behaviour:** I do not have the options of the moderator - no filtering or marking of the questions
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)
**Importance:** Quite important for Schulung at nexus tomorrow

**Comment by hmkay** [comment]
**URL:** https://speakup.digital/projects/eure-fragen-zu-speakup/
**user:** moderation
**expected behaviour:** I can moderate the incoming questions
**behaviour:** I do not have the options of the moderator - no filtering or marking of the questions
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)
**Importance:** Quite important for Schulung at nexus tomorrow

**Comment by hmkay** [comment]
Apparently the invite via dashboard worked, but I cannot access the functions of the mdoeration such as marking questions as answered, etc pp

**Comment by fuzzylogic2000** [comment]
It is working! :)
