### ISSUE TITLE
presentation screen: space between URL and "unter" 

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#312]
**URL:** https://speakup.digital/questions/present/module/speak-up-14/
**user:** user
**expected behaviour:** there is a space between the URL and the "mitmachen unter"
**behaviour:** no space: "unterhttps://speakup.digital/projects/eure-fragen-zu-speakup/"
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)
**Importance:** not urgent, but would look good

**Comment by hmkay** [comment]
![Bildschirmfoto 2019-09-09 um 15 49 35](https://user-images.githubusercontent.com/30862422/64536823-0cde0c80-d31a-11e9-8d9e-157cec88b908.png)

**Comment by fuzzylogic2000** [comment]
I think it got lost in the translation.
