### ISSUE TITLE
Important issue testing

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#349]
Please, fill in this template in order to help us understand the issue better

**URL:** liqd.net
**user:** *moderator*
**expected behaviour:** asdad
**behaviour:** asdasdasd
**important screensize:** mobile
**device & browser:** Firefox
**Comment/Question: ** Why?

**Comment by fuzzylogic2000** [comment]
:p

**Comment by hmkay** [comment]
xD Thanks for checking the issues, @fuzzylogic2000
