### ISSUE TITLE
Make project: hide "learn more" link

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#36]
If I do a new project, I am asked to "use the template" or to "learn more". The learn more link does not lead anywhere so far, could we hide it for the moment?

![learn more and SU Icon](https://user-images.githubusercontent.com/30862422/55164137-6d61fe80-516b-11e9-8599-2132f6bc4db8.jpeg)

**Comment by hmkay** [comment]
ok I just noticed this is a really realy minor issue. Please do not take it into consideration until we actually work on the dashboard for externals!

**Comment by phillimorland** [comment]
fixed in previous pull
