### ISSUE TITLE
Re-name "Anmeldung/Register

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#40]
To indicate that the menu is only for moderators/admins?

**Comment by hmkay** [comment]
Possible re-name could be: "Moderators sign-in" or "admin" or "moderator"...

**Comment by phillimorland** [comment]
@hmkay do you have a final choice on this? I have seen "admin" buttons commonly used on other sites but not sure if that's correct use in this case

**Comment by hmkay** [comment]
Hm. Could we hide the "sign in/register" button on the landing page and re-name the sign-in/register button on the project page "For Moderators"? Is that possible?

**Comment by phillimorland** [comment]
@hmkay it is easy but I don't think removing the entrance point to creating an event from the homepage is a good idea from user point of view, what do you think @szukowski?

**Comment by hmkay** [comment]
@MagdaN had the idea to put it in the footer

**Comment by szukowski** [comment]
to clearly separate the accesses, we would need two links.
the first for moderators etc. with login
the second link for visitors without login. if necessary, this is created when you have created an event?

or an upstream selection. "Login" if moderator or "start event" if visitor

without generating any costs, leave the login above.

**Comment by phillimorland** [comment]
@hmkay ahhh this is relevant to previous issue, do we need to discuss?
