### ISSUE TITLE
What happens to speakup?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#425]
We are currently pretty much ignoring speakup update-wise. What will happen to it? Do we want to keep it running @hmkay ? Then we should update and deploy!

**Comment by hmkay** [comment]
@fuzzylogic2000 : Could we do it this time? Is it a lot of work? I guess this would be the last time, but maybe it would be nice to have it running - if it is not too much of a huzzle!

**Comment by fuzzylogic2000** [comment]
Yeah, we kinda have to. :)

**Comment by hmkay** [comment]
;)

**Comment by fuzzylogic2000** [comment]
So, we decided it should still run! But how long? Because every project needs these updates regularly and every time stuff might break...

**Comment by hmkay** [comment]
Yes. I totally see that. I suggest we wait until the interactive event is implemented in meinBerlin (that´s the plan, right @CarolingerSeilchenspringer ?) to then put it into archive. What do you think, @fuzzylogic2000 ? I will make a MMM proposal as well!

**Comment by fuzzylogic2000** [comment]
Cool!

**Comment by hmkay** [comment]
Ha! You were quick! I edited my comment (FYI). But nevertheless - to close it is gooooood!

**Comment by CarolingerSeilchenspringer** [comment]
totally agree and yes, it will be implemented in meinBerlin, maybe even in upcoming sprint.
