### ISSUE TITLE
Registration - add space between "Rand" and form

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-speakup#82]
The form is pretty close to the edge. Is there a possibility to put more space between it?
![Issue_registrierung](https://user-images.githubusercontent.com/30862422/56132029-45ef9c00-5f89-11e9-8903-32ecb2ab2490.png)

**Comment by fuzzylogic2000** [comment]
Well, sure, there's always the possibility to have sth. look different. But are we meant to and how much time should we invest? Ok, I guess, it doesn't take much time, but then there are more pages to check and add more space.

**Comment by hmkay** [comment]
nah, it´s not a high prio thing. It would be a "let´s make it shiny" -thing, but there are otehr issues that are more important!
