### ISSUE TITLE
still have access to 'bearbeiten' button as moderator

### ISSUE THREAD

**Issue by shuehne** [liqd/a4-speakup#86]
My account (s.huehne1 - email address: s.huehne+mod@liqd.net) has moderator rights for the SpeakUp Review project. However, as moderator, I still have access to the 'bearbeiten' button on the main page, which lets me change the Grundeinstellungen. I guess that that shouldn't happen. My other account (s.huehne - email address: s.huehne@liqd.net) has admin rights.

**Comment by MagdaN** [comment]
as a moderator you are allowed to change project setting - so this is a feature :-)

**Comment by shuehne** [comment]
Mh, MK had a different idea I think. Maybe we need to discuss this again.

**Comment by MagdaN** [comment]
@shuehne @hmkay then we should discuss this

**Comment by hmkay** [comment]
@MagdaN  @shuehne  I understood it the way that admins do have dashboard access and moderators don´t. As the dashboard wasn´t the prio, I would also like to keep it out of moderators access. It is just a little untidy for outside people. So could we remove the "bearbeiten" button?

**Comment by hmkay** [comment]
@fuzzylogic2000  @phillimorland  this would be important for the release...sorry, I don´t know how to add the milestone!

**Comment by fuzzylogic2000** [comment]
@hmkay Does the link to the dashboard stay in the user (moderator) dropdown? I guess not? How do moderators find their projects, then? Should I add a list of the projects to the user dropdown for now? Will make new issue!

**Comment by fuzzylogic2000** [comment]
@hmkay, wait, no, let's talk about it on Monday and for now, I will remove the button for moderators!
